apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-application-postgresql-pvc
  labels:
    app: todo-application
    type: pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi